### PR TITLE
delete "bias" from "loss_fn" "return" in "histogramvae.py"

### PR DESCRIPTION
**Pull request by Samir-atra**

### CODE REVIEW

**Comment by egesko** [comment]
Closes #125 .

**Comment by egesko** [comment]
Thanks @Samir-atra  for attending to this. Would you be able to update [train_step line](https://github.com/themis-ai/capsa/blob/69287b7153f551b7eb02888e0b59bcb66e034e8b/capsa/bias/histogramvae.py#L226) as well so that it works with newly updated `loss_fn()`? 
Thank you!

**Comment by egesko** [comment]
Actually, we can completely delete `train_step()` from HistogramVAEWrapper class because of the fact the updated version would be [identical the `train_step()` implementation in BaseWrapper parent class](https://github.com/themis-ai/capsa/blob/69287b7153f551b7eb02888e0b59bcb66e034e8b/capsa/base_wrapper.py#L62-L111).

**Comment by Samir-atra** [comment]
Thank you, I made the other two edits.

**Review by egesko — APPROVED** [review]
Looks good to me! Thanks for updating the code!

**Pull request merged**
